#!/usr/bin/env python3
"""Declare whole runs of same-sized functions in one pass.

`recover_gaps.py` recovers one function per gap per pass, because `end` is only
an upper bound and codegen stops at the first function it finds. Where a gap
holds a *run* of identically-sized functions - this image has long tables of
0x18-byte wrappers - that costs one full codegen per function.

This fills such runs directly. For each remaining gap it takes the stride from
the function immediately before the gap, checks that the gap is a whole number
of strides, and declares every slot in the run. Codegen still validates: a wrong
stride shows up as an undecodable range or an escaping branch, and
`prune_epilogue_gaps.py` removes anything malformed.

Only uniform runs are touched. A gap whose length is not a multiple of the
preceding function's size is left for the normal loop.

Usage:
    python tools/fill_chains.py            # report
    python tools/fill_chains.py --apply
"""

import argparse
import io
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GEN = ROOT / "generated" / "default"
GAPS = ROOT / "nbajam_ofe_gaps.toml"
BANLIST = ROOT / "tools" / "gap_banlist.txt"

TAIL_DATA_START = 0x82B17E1C
CODE_HI = 0x82B19930
MIN_GAP = 8

FN_DEF = re.compile(r"^DEFINE_REX_FUNC\(([A-Za-z_][A-Za-z0-9_]*)\)\s*\{")
INSN = re.compile(r"^\t// [a-z][a-z0-9_.]*(\s|$)")
SETFN = re.compile(r"SetFunction\(0x([0-9A-F]+),\s*([A-Za-z_][A-Za-z0-9_]*)\)")
DECL = re.compile(r'^"0x([0-9A-F]+)"\s*=\s*\{\s*end\s*=\s*0x([0-9A-F]+)')


def measure():
    text = (GEN / "nbajam_ofe_register.cpp").read_text(encoding="utf-8", errors="replace")
    addr_of = {m.group(2): int(m.group(1), 16) for m in SETFN.finditer(text)}
    sizes = {}
    for path in sorted(GEN.glob("nbajam_ofe_recomp.*.cpp")):
        cur, n = None, 0
        with path.open(encoding="utf-8", errors="replace") as fh:
            for line in fh:
                m = FN_DEF.match(line)
                if m:
                    if cur:
                        sizes[cur] = n
                    cur, n = m.group(1), 0
                elif cur and INSN.match(line):
                    n += 1
        if cur:
            sizes[cur] = n
    return {addr_of[k]: v * 4 for k, v in sizes.items() if k in addr_of and v}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    args = ap.parse_args()

    funcs = measure()
    addrs = sorted(funcs)

    decls = {}
    for line in io.open(GAPS, encoding="utf-8").read().splitlines():
        m = DECL.match(line)
        if m:
            decls[int(m.group(1), 16)] = int(m.group(2), 16)

    banned = set()
    if BANLIST.exists():
        for line in io.open(BANLIST, encoding="utf-8").read().splitlines():
            tok = line.split("#")[0].strip()
            if tok:
                banned.add(int(tok, 16))

    added = 0
    runs = 0
    for i, a in enumerate(addrs):
        end = a + funcs[a]
        nxt = addrs[i + 1] if i + 1 < len(addrs) else CODE_HI
        gap = nxt - end
        if gap < MIN_GAP or end >= TAIL_DATA_START:
            continue
        stride = funcs[a]
        if stride < 8 or gap % stride != 0:
            continue
        slots = gap // stride
        if slots < 2:
            continue
        # Every slot is set to exactly one stride, including any already
        # declared. The first slot of a run normally carries a wide `end`
        # spanning the whole gap (that is how the per-gap loop declares it);
        # leaving it wide makes the slots that follow overlap it, and codegen
        # rejects overlaps outright:
        #   Overlapping boundaries: 0x82B09D10+0xD8 overlaps 0x82B09D28+0x18
        new = []
        for k in range(slots):
            s = end + k * stride
            if s in banned:
                continue
            if decls.get(s) == s + stride:
                continue
            new.append((s, s + stride))
        if not new:
            continue
        runs += 1
        print("  0x{:08X}..0x{:08X}  stride 0x{:X}  {} slots, {} new (after sub_{:08X})".format(
            end, nxt, stride, slots, len(new), a))
        for s, e in new:
            decls[s] = e
            added += 1

    print("\n{} uniform runs, {} declarations to add, {} total".format(runs, added, len(decls)))
    if not args.apply or not added:
        if not args.apply:
            print("(report only; pass --apply)")
        return 0

    header = [
        "# NBA JAM: On Fire Edition - recovered gap functions",
        "#",
        "# Generated by tools/recover_gaps.py and tools/fill_chains.py, filtered by",
        "# tools/prune_epilogue_gaps.py. `end` is an upper bound; codegen stops at",
        "# the real end of each function. See BUILDING.md.",
        "#",
        "# {} entries.".format(len(decls)),
        "",
        "[functions]",
    ]
    body = ['"0x{:08X}" = {{ end = 0x{:08X} }}'.format(a, e) for a, e in sorted(decls.items())]
    io.open(GAPS, "w", encoding="utf-8", newline="\n").write("\n".join(header + body) + "\n")
    print("wrote {}".format(GAPS.name))
    return 0


if __name__ == "__main__":
    sys.exit(main())
