#!/usr/bin/env python3
"""Swap ReXGlue's emitted code for chosen vector opcodes inside one function.

The EA Sports intro decodes wrong. sub_824E5FD8, the block writer, was cleared
by reimplementing it natively and getting byte-identical output, so the fault
is upstream in sub_824E6310 - 3022 instructions of VP6 coefficient decoding and
IDCT. Reading the SDK's vector builders against the PowerPC spec found nothing,
so this tests them instead.

For each instruction of a chosen opcode inside a chosen function, the emitted
C++ is replaced with a call to the matching reference implementation in
src/vp6_refops.h, written independently from the spec. Rebuild, run, and
compare the decoded frame against ffmpeg: if the corruption goes away, the
opcode that was swapped is the one ReXGlue gets wrong.

The generated file is regenerated by codegen only when the config changes, so
a patch survives an ordinary rebuild. --restore puts the original back.

Usage:
    python tools/patch_refops.py --list
    python tools/patch_refops.py --ops all
    python tools/patch_refops.py --ops vsraw128,vaddsws
    python tools/patch_refops.py --restore
"""

import argparse
import io
import re
import shutil
import sys
from pathlib import Path

FUNC = ""

ROOT = Path(__file__).resolve().parent.parent
GEN = ROOT / "generated" / "default"
DEFAULT_FUNC = "sub_824E6310"

INSN = re.compile(r"^\t// ([a-z][a-z0-9_.]*)\s*(.*)$")
VREG = re.compile(r"^v(\d+)$")
# Branch targets sit between instructions and must survive a replacement, or
# the goto that jumps to them stops compiling.
LABEL = re.compile(r"^\s*loc_[0-9A-Fa-f]+:\s*$")

# opcode -> (reference function, how to build its argument list).
# "d,a,b" means vD, vA, vB; a trailing "#N" takes operand N as an integer.
SPEC = {
    "vaddsws":     ("vp6ref::vaddsws",   "d,a,b"),
    "vsubsws":     ("vp6ref::vsubsws",   "d,a,b"),
    "vaddshs":     ("vp6ref::vaddshs",   "d,a,b"),
    "vsraw":       ("vp6ref::vsraw",     "d,a,b"),
    "vsraw128":    ("vp6ref::vsraw",     "d,a,b"),
    "vsrw":        ("vp6ref::vsrw",      "d,a,b"),
    "vsrw128":     ("vp6ref::vsrw",      "d,a,b"),
    "vslw":        ("vp6ref::vslw",      "d,a,b"),
    "vslw128":     ("vp6ref::vslw",      "d,a,b"),
    "vpkshus":     ("vp6ref::vpkshus",   "d,a,b"),
    "vpkshus128":  ("vp6ref::vpkshus",   "d,a,b"),
    "vpkswss":     ("vp6ref::vpkswss",   "d,a,b"),
    "vpkuwus":     ("vp6ref::vpkuwus",   "d,a,b"),
    "vpkuwus128":  ("vp6ref::vpkuwus",   "d,a,b"),
    "vor":         ("vp6ref::vor",       "d,a,b"),
    "vor128":      ("vp6ref::vor",       "d,a,b"),
    "vmrghb":      ("vp6ref::vmrghb",    "d,a,b"),
    "vmaddfp":     ("vp6ref::vmaddfp",   "d,a,b,c"),
    "vmaddfp128":  ("vp6ref::vmaddfp",   "d,a,b,c"),
    "vrfiz":       ("vp6ref::vrfiz",     "d,a"),
    "vrfiz128":    ("vp6ref::vrfiz",     "d,a"),
    "vcuxwfp128":  ("vp6ref::vcuxwfp",   "d,a,#2"),
    "vcfux":       ("vp6ref::vcuxwfp",   "d,a,#2"),
    "vcfpuxws128": ("vp6ref::vcfpuxws",  "d,a,#2"),
    "vctuxs":      ("vp6ref::vcfpuxws",  "d,a,#2"),
    "vpkswss128":  ("vp6ref::vpkswss",   "d,a,b"),
    "vperm":       ("vp6ref::vperm",     "d,a,b,c"),
    "vperm128":    ("vp6ref::vperm",     "d,a,b,c"),
    "vsldoi":      ("vp6ref::vsldoi",    "d,a,b,#3"),
    "vsldoi128":   ("vp6ref::vsldoi",    "d,a,b,#3"),
    "vmrghw":      ("vp6ref::vmrghw",    "d,a,b"),
    "vmrghw128":   ("vp6ref::vmrghw",    "d,a,b"),
    "vmrglw":      ("vp6ref::vmrglw",    "d,a,b"),
    "vmrglw128":   ("vp6ref::vmrglw",    "d,a,b"),
    "vupkhsb":     ("vp6ref::vupkhsb",   "d,a"),
    "vupkhsb128":  ("vp6ref::vupkhsb",   "d,a"),
    "vupklsb":     ("vp6ref::vupklsb",   "d,a"),
    "vupklsb128":  ("vp6ref::vupklsb",   "d,a"),
    "vupkhsh":     ("vp6ref::vupkhsh",   "d,a"),
    "vupklsh":     ("vp6ref::vupklsh",   "d,a"),
    "vspltw":      ("vp6ref::vspltw",    "d,a,#2"),
    "vspltw128":   ("vp6ref::vspltw",    "d,a,#2"),
    "vmulfp":      ("vp6ref::vmulfp",    "d,a,b"),
    "vmulfp128":   ("vp6ref::vmulfp",    "d,a,b"),
    "vaddfp":      ("vp6ref::vaddfp",    "d,a,b"),
    "vaddfp128":   ("vp6ref::vaddfp",    "d,a,b"),
    "vsubfp":      ("vp6ref::vsubfp",    "d,a,b"),
    "vsubfp128":   ("vp6ref::vsubfp",    "d,a,b"),
    "vcsxwfp128":  ("vp6ref::vcsxwfp",   "d,a,#2"),
    "vcfsx":       ("vp6ref::vcsxwfp",   "d,a,#2"),
    "vcfpsxws128": ("vp6ref::vcfpsxws",  "d,a,#2"),
    "vctsxs":      ("vp6ref::vcfpsxws",  "d,a,#2"),
}

# Vector memory opcodes. Their emitted code is two lines: the first computes
# the effective address into `ea` or `temp.u32`, the second does the transfer.
# Only the second is replaced, so the address arithmetic stays exactly as
# codegen produced it and only the load/store semantics are under test.
MEM_SPEC = {
    "lvx":       "vp6ref::lvx",
    "lvx128":    "vp6ref::lvx",
    "lvlx":      "vp6ref::lvlx",
    "lvlx128":   "vp6ref::lvlx",
    "lvrx":      "vp6ref::lvrx",
    "lvrx128":   "vp6ref::lvrx",
    "stvx":      "vp6ref::stvx",
    "stvx128":   "vp6ref::stvx",
    "stvewx":    "vp6ref::stvewx",
    "stvewx128": "vp6ref::stvewx",
}
EA_LINE = re.compile(r"^\t(ea|temp\.u32)\s*=")


def gen_file():
    marker = "DEFINE_REX_FUNC({})".format(FUNC)
    for path in sorted(GEN.glob("nbajam_ofe_recomp.*.cpp")):
        if marker in io.open(path, encoding="utf-8", errors="replace").read():
            return path
    return None


def split_operands(text):
    """'v13,v0,v5' -> ['v13', 'v0', 'v5'] (drops any trailing comment)."""
    text = text.split("//")[0].strip()
    return [t.strip() for t in text.split(",") if t.strip()] if text else []


def reg_expr(tok):
    m = VREG.match(tok)
    return "ctx.v{}".format(m.group(1)) if m else None


def build_call(op, ops):
    # VMX128 reuses the vupkhsb128/vupklsb128 encodings for vupkhsh/vupklsh
    # when the third operand field is 0x60. The disassembly comment keeps the
    # byte mnemonic, so the operand has to be checked here too.
    if op in ("vupkhsb128", "vupklsb128") and len(ops) > 2 and ops[2] == "v96":
        op = "vupkhsh" if op == "vupkhsb128" else "vupklsh"
    fn, sig = SPEC[op]
    args = []
    for part in sig.split(","):
        if part.startswith("#"):
            idx = int(part[1:])
            if idx >= len(ops):
                return None
            tok = ops[idx]
            try:
                args.append(str(int(tok, 0)))
            except ValueError:
                return None
        else:
            pos = {"d": 0, "a": 1, "b": 2, "c": 3}[part]
            if pos >= len(ops):
                return None
            e = reg_expr(ops[pos])
            if e is None:
                return None
            args.append(e)
    return "\t{}({});".format(fn, ", ".join(args))


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("--ops", default="", help="comma separated, or 'all'")
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--restore", action="store_true")
    ap.add_argument("--func", default=DEFAULT_FUNC)
    ap.add_argument("--alias-only", action="store_true",
                    help="only instructions whose destination is also a source")
    args = ap.parse_args(argv)
    global FUNC
    FUNC = args.func

    path = gen_file()
    if path is None:
        print("{} not found in generated sources".format(FUNC))
        return 1
    backup = path.with_suffix(path.suffix + ".orig")

    if args.restore:
        if backup.exists():
            shutil.copyfile(backup, path)
            print("restored {}".format(path.name))
        else:
            print("no backup to restore")
        return 0

    if not backup.exists():
        shutil.copyfile(path, backup)
        print("saved {}".format(backup.name))
    # Always patch from the pristine copy so runs do not compound.
    text = io.open(backup, encoding="utf-8", errors="replace").read()
    lines = text.split("\n")

    start = next(i for i, l in enumerate(lines) if l.startswith("DEFINE_REX_FUNC({})".format(FUNC)))
    end = next(i for i in range(start + 1, len(lines)) if lines[i].startswith("DEFINE_REX_FUNC("))

    if args.list:
        counts = {}
        for l in lines[start:end]:
            m = INSN.match(l)
            if m:
                counts[m.group(1)] = counts.get(m.group(1), 0) + 1
        print("{}: {} instructions".format(FUNC, sum(counts.values())))
        for op, n in sorted(counts.items(), key=lambda kv: -kv[1]):
            mark = "patchable" if op in SPEC else ("memory" if op in MEM_SPEC else "")
            if mark:
                print("  {:14s} x{:<5d} {}".format(op, n, mark))
        return 0

    if args.ops == "all":
        wanted = set(SPEC) | set(MEM_SPEC)
    elif args.ops == "alu":
        wanted = set(SPEC)
    elif args.ops == "mem":
        wanted = set(MEM_SPEC)
    else:
        wanted = set(o.strip() for o in args.ops.split(",") if o.strip())
    if not wanted:
        print("nothing to do; pass --ops")
        return 2
    unknown = wanted - set(SPEC) - set(MEM_SPEC)
    if unknown:
        print("not patchable: {}".format(", ".join(sorted(unknown))))
        return 2

    out = lines[:start]
    i = start
    patched = {}
    skipped = {}
    while i < end:
        line = lines[i]
        m = INSN.match(line)
        if not m or m.group(1) not in wanted:
            out.append(line)
            i += 1
            continue
        op, rest = m.group(1), m.group(2)
        ops_toks = split_operands(rest)
        if args.alias_only:
            regs = [t for t in ops_toks if VREG.match(t)]
            if not (len(regs) >= 2 and regs[0] in regs[1:]):
                out.append(line)
                i += 1
                continue
        if op in MEM_SPEC:
            # Keep codegen's address line, replace only the transfer.
            j = i + 1
            labels = []
            ea_lines = []
            while j < end and not INSN.match(lines[j]):
                if LABEL.match(lines[j]):
                    labels.append(lines[j])
                elif EA_LINE.match(lines[j]):
                    ea_lines.append(lines[j])
                j += 1
            vreg = reg_expr(ops_toks[0]) if ops_toks else None
            if vreg is None or not ea_lines:
                skipped[op] = skipped.get(op, 0) + 1
                out.extend(lines[i:j])
            else:
                ea_var = "ea" if ea_lines[-1].lstrip().startswith("ea") else "temp.u32"
                out.append(line)
                out.extend(ea_lines)
                out.append("	{}({}, {});".format(MEM_SPEC[op], vreg, ea_var))
                out.extend(labels)
                patched[op] = patched.get(op, 0) + 1
            i = j
            continue
        call = build_call(op, ops_toks)
        # Emitted C++ for this instruction runs until the next "// <mnemonic>".
        j = i + 1
        labels = []
        while j < end and not INSN.match(lines[j]):
            if LABEL.match(lines[j]):
                labels.append(lines[j])
            j += 1
        if call is None:
            skipped[op] = skipped.get(op, 0) + 1
            out.extend(lines[i:j])
        else:
            out.append(line)
            out.append(call)
            out.extend(labels)
            patched[op] = patched.get(op, 0) + 1
        i = j
    out.extend(lines[end:])

    body = "\n".join(out)
    inc = '#include "../../src/vp6_refops.h"'
    if inc not in body:
        # Put it after the last #include at the top of the file.
        idx = body.rfind("#include", 0, body.find("DEFINE_REX_FUNC"))
        eol = body.find("\n", idx)
        body = body[:eol + 1] + inc + "\n" + body[eol + 1:]
    io.open(path, "w", encoding="utf-8", newline="\n").write(body)

    total = sum(patched.values())
    print("patched {} instructions in {} ({})".format(total, FUNC, path.name))
    for op, n in sorted(patched.items(), key=lambda kv: -kv[1]):
        print("   {:14s} x{}".format(op, n))
    for op, n in sorted(skipped.items()):
        print("   skipped {:14s} x{} (unrecognised operands)".format(op, n))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
