#!/usr/bin/env python3
"""Generate uniquely-named mid-ASM probes for one function.

The earlier probe tool bound one hook name to many addresses, which made the
output ambiguous: a poisoned register reading could not be attributed to a
particular site. This emits one hook *per site*, named after its address, so
every line in hooks.txt says exactly where it came from.

Writes three files:
    nbajam_ofe_hooks.toml     the [[midasm_hook]] entries
    src/nbajam_probes.h       declarations
    src/nbajam_probes.cpp     definitions, each forwarding to NbaProbeSite()

Usage:
    python tools/probe_sites.py sub_82558718
    python tools/probe_sites.py sub_82558718 sub_8255AEB8
"""

import glob
import io
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GEN = ROOT / "generated" / "default"

REGS = ["r1", "r31"]


def find_function(name):
    marker = "DEFINE_REX_FUNC({})".format(name)
    for path in sorted(GEN.glob("nbajam_ofe_recomp.*.cpp")):
        text = io.open(path, encoding="utf-8", errors="replace").read()
        if marker not in text:
            continue
        lines = text.split("\n")
        start = next(i for i, l in enumerate(lines) if l.startswith(marker))
        end = next((i for i in range(start + 1, len(lines))
                    if lines[i].startswith("DEFINE_REX_FUNC(")), len(lines))
        return path, lines[start:end]
    return None, None


def sites_for(name):
    """(address, description) for the entry and every call return."""
    path, body = find_function(name)
    if body is None:
        return []
    out = []
    addr = int(name[4:], 16) if name.startswith("sub_") else None
    if addr is not None:
        out.append((addr, "{} entry".format(name)))
    for i, line in enumerate(body):
        m = re.match(r"\tctx\.lr = 0x([0-9A-F]+);", line)
        if not m:
            continue
        callee = body[i + 1].strip().replace("(ctx, base);", "").strip()
        out.append((int(m.group(1), 16), "in {} after {}".format(name, callee)))
    return out


def main(argv):
    names = [a for a in argv if a.startswith("sub_")]
    if not names:
        print(__doc__)
        return 2

    all_sites = []
    for n in names:
        s = sites_for(n)
        print("{}: {} sites".format(n, len(s)))
        all_sites.extend(s)

    if not all_sites:
        print("no sites found")
        return 1

    decls, defs, toml = [], [], []
    toml.append("# NBA JAM: On Fire Edition - per-site register probes\n"
                "#\n"
                "# Generated by tools/probe_sites.py. Every site has its own hook name so\n"
                "# each line in hooks.txt is attributable. See BUILDING.md.\n"
                'template_dir = "templates"\n')

    for addr, desc in all_sites:
        fn = "NbaProbe_{:08X}".format(addr)
        decls.append("void {}(PPCRegister& r1, PPCRegister& r31);  // {}".format(fn, desc))
        defs.append('void {}(PPCRegister& r1, PPCRegister& r31) {{\n'
                    '  NbaProbeSite("0x{:08X}  {}", r1, r31);\n'
                    '}}'.format(fn, addr, desc))
        toml.append('\n[[midasm_hook]]\naddress = 0x{:08X}  # {}\nname = "{}"\nregisters = ["r1", "r31"]\n'
                    .format(addr, desc, fn))

    io.open(ROOT / "nbajam_ofe_hooks.toml", "w", encoding="utf-8", newline="\n").write("".join(toml))

    io.open(ROOT / "src" / "nbajam_probes.h", "w", encoding="utf-8", newline="\n").write(
        "// Generated by tools/probe_sites.py - do not edit by hand.\n"
        "//\n"
        "// One hook per probe site, so every reading in hooks.txt is attributable\n"
        "// to a specific guest address.\n\n"
        "#pragma once\n\n"
        "#include <rex/ppc/context.h>\n\n"
        "void NbaProbeSite(const char* label, PPCRegister& r1, PPCRegister& r31);\n\n"
        + "\n".join(decls) + "\n")

    io.open(ROOT / "src" / "nbajam_probes.cpp", "w", encoding="utf-8", newline="\n").write(
        "// Generated by tools/probe_sites.py - do not edit by hand.\n\n"
        '#include "nbajam_probes.h"\n\n'
        + "\n\n".join(defs) + "\n")

    print("wrote {} probes".format(len(all_sites)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
