#!/usr/bin/env python3
"""Generate r1 probes for a set of recompiled functions.

Emits a mid-ASM hook at each named function's entry and at the return address
of every call it makes, all bound to NbaTraceR1. Running the build then prints
the guest stack pointer at each of those points in execution order, so the
first misaligned reading brackets the call that lost it.

Usage:
    python tools/probe_r1.py sub_823977B8 sub_82558820
    python tools/probe_r1.py --clear

Writes nbajam_ofe_hooks.toml, which the manifest includes.
"""

import glob
import io
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GEN = ROOT / "generated" / "default"
OUT = ROOT / "nbajam_ofe_hooks.toml"

HEADER = """# NBA JAM: On Fire Edition - r1 probes (generated by tools/probe_r1.py)
#
# The guest stack pointer is intact on entry to xstart (0x70170000, aligned)
# and broken by the time the game reaches the kernel. Probing narrows where.
# Chain established so far:
#   xstart -> sub_82246B10 (CRT _initterm)
#          -> indirect call to 0x82AF88E8, which returns with r1 broken
#   sub_82AF88E8 itself is well formed, so one of its two callees is at fault.
#
# template_dir also brings in the guard added to REX_CALL_INDIRECT_FUNC.
template_dir = "templates"

[[midasm_hook]]
address = 0x82246498  # xstart entry, baseline
name = "NbaTraceR1"
registers = ["r1"]

[[midasm_hook]]
address = 0x82AF88E8  # entry of the initializer that returns with r1 broken
name = "NbaTraceR1"
registers = ["r1"]

[[midasm_hook]]
address = 0x82AF890C  # after sub_823977B8
name = "NbaTraceR1"
registers = ["r1"]

[[midasm_hook]]
address = 0x82AF8918  # after sub_82558820
name = "NbaTraceR1"
registers = ["r1"]
"""

PROBE = '\n[[midasm_hook]]\naddress = 0x{:08X}  # {}\nname = "NbaTraceR1"\nregisters = ["r1"]\n'


def find_function(name):
    """Return (path, body_lines) for a recompiled function, or None."""
    marker = "DEFINE_REX_FUNC({})".format(name)
    for path in sorted(GEN.glob("nbajam_ofe_recomp.*.cpp")):
        text = io.open(path, encoding="utf-8", errors="replace").read()
        if marker not in text:
            continue
        lines = text.split("\n")
        start = next(i for i, l in enumerate(lines) if l.startswith(marker))
        end = next((i for i in range(start + 1, len(lines))
                    if lines[i].startswith("DEFINE_REX_FUNC(")), len(lines))
        return path, lines[start:end]
    return None


def main(argv):
    if "--clear" in argv:
        io.open(OUT, "w", encoding="utf-8", newline="\n").write(
            "# No probes active.\ntemplate_dir = \"templates\"\n")
        print("cleared")
        return 0

    names = [a for a in argv if a.startswith("sub_") or a == "xstart"]
    if not names:
        print(__doc__)
        return 2

    parts = [HEADER]
    for name in names:
        found = find_function(name)
        if not found:
            print("not found: {}".format(name))
            continue
        path, body = found
        addr = int(name[4:], 16) if name.startswith("sub_") else 0x82246498
        parts.append(PROBE.format(addr, "{} entry".format(name)))
        n = 0
        for i, line in enumerate(body):
            m = re.match(r"\tctx\.lr = 0x([0-9A-F]+);", line)
            if not m:
                continue
            callee = body[i + 1].strip() if i + 1 < len(body) else "?"
            callee = callee.replace("(ctx, base);", "").strip()
            parts.append(PROBE.format(int(m.group(1), 16),
                                      "in {} after {}".format(name, callee)))
            n += 1
        print("{}: {} lines, {} call probes  ({})".format(name, len(body), n, path.name))

    io.open(OUT, "w", encoding="utf-8", newline="\n").write("".join(parts))
    print("wrote {} with {} probes".format(OUT.name, "".join(parts).count("[[midasm_hook]]")))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
