// NBA JAM: On Fire Edition - mid-ASM diagnostic hooks
//
// Codegen emits an `extern` declaration for each of these into the generated
// source, so nothing has to be included anywhere for it to see them. This
// header exists for the implementation file and for readers.
//
// Observation only: none of these return a value, so none can alter guest
// control flow. They answer questions the runtime log cannot, because it sees
// kernel calls but not the guest state that produced their arguments.

#pragma once

#include <rex/ppc/context.h>

// The game's NtReadFile wrapper sub_82552730(fileObj, buffer, length, offset).
void NbaTraceFileReadEntry(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5,
                           PPCRegister& r6);

// Reports the guest stack pointer on entry to a function. Registered at every
// address in the call chains that reach the kernel, to bracket where r1 stops
// being a real stack address.
void NbaTraceR1(PPCRegister& r1);

// Shared implementation behind the per-site probes generated by
// tools/probe_sites.py.
void NbaProbeSite(const char* label, PPCRegister& r1, PPCRegister& r31);

// sub_82558718 restores the stack pointer from r31 (addi r1,r31,176), and
// returns with r1 = 0xBEBEBF6E, so r31 is 0xBEBEBEBE -- the byte pattern the
// runtime fills new thread stacks with. This reports the first probe where r31
// has picked up that pattern, to find the call that fails to preserve it.
void NbaTraceR31(PPCRegister& r1, PPCRegister& r31);

// Called after every indirect call by the guard in the overridden PCH
// template; reports the first call that returns with a broken stack pointer.
struct PPCContext;
void NbaCheckR1(uint32_t target, uint32_t r1_before, PPCContext& ctx);

// Each `bl` to the NtCreateFile import. The failing read of memory.cfg is
// reached by a path that is not one of the three direct NtReadFile call sites,
// so these print a resolved call stack to find out which guest code is really
// driving the file system.
void NbaCreateSite1(PPCRegister& r3, PPCRegister& r4);
void NbaCreateSite2(PPCRegister& r3, PPCRegister& r4);
void NbaCreateSite3(PPCRegister& r3, PPCRegister& r4);
void NbaCreateSite4(PPCRegister& r3, PPCRegister& r4);
void NbaCreateSite5(PPCRegister& r3, PPCRegister& r4);

// Each `bl` to the NtReadFile import, with the full argument set.
void NbaReadSite1(PPCRegister& r3, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9,
                  PPCRegister& r10);
void NbaReadSite2(PPCRegister& r3, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9,
                  PPCRegister& r10);
void NbaReadSite3(PPCRegister& r3, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9,
                  PPCRegister& r10);
